# Generated by Django 5.2.1 on 2025-05-23 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_section_product_additional_information_product_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='App_Product',
        ),
    ]
