# Generated by Django 5.2.1 on 2025-05-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
