# Generated by Django 5.2.1 on 2025-05-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
