# Generated by Django 5.2.1 on 2025-06-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
