# Generated by Django 5.2.1 on 2025-06-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
