# Generated by Django 5.2.1 on 2025-06-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
