# Generated by Django 5.2.1 on 2025-06-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_on',
        ),
    ]
