# Generated by Django 5.2.1 on 2025-06-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
