# Generated by Django 5.2.1 on 2025-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_area',
            name='Deal',
            field=models.CharField(choices=[('Bestseller Products', 'Bestseller Products'), ('Featured Products', 'Featured Products')], max_length=100, null=True),
        ),
    ]
