# Generated by Django 5.2.1 on 2025-06-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_banner_area_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/banner_img')),
                ('Deal', models.CharField(choices=[('Bestseller Products', 'Bestseller Products'), ('Featured Products', 'Featured Products')], max_length=100, null=True)),
                ('Discount_Deal', models.CharField(max_length=100)),
                ('Quote', models.CharField(max_length=100)),
                ('Discount', models.IntegerField()),
                ('Link', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='banner_area',
            name='Deal',
        ),
    ]
