# Generated by Django 5.2.1 on 2025-06-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_banner_remove_banner_area_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Image',
            field=models.ImageField(upload_to='banner_img'),
        ),
    ]
