# Generated by Django 5.2.1 on 2025-06-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_alter_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='Discount_Deal',
        ),
    ]
