# Generated by Django 5.2.1 on 2025-06-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_remove_banner_discount_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='brands/'),
        ),
    ]
