# Generated by Django 5.2.1 on 2025-06-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='bannerss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/banner_section')),
                ('Quote', models.CharField(max_length=100)),
                ('Discount', models.IntegerField()),
                ('Link', models.CharField(max_length=200, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.banner_section')),
            ],
        ),
    ]
