# Generated by Django 5.2.1 on 2025-06-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_banner_section_bannerss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bannerss',
            new_name='ban_section',
        ),
    ]
