# Generated by Django 5.2.1 on 2025-06-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_rename_bannerss_ban_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ban_section',
            old_name='section',
            new_name='sectionn',
        ),
    ]
