# Generated by Django 5.2.1 on 2025-06-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_rename_section_ban_section_sectionn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
