# Generated by Django 5.2.1 on 2025-06-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_alter_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner_area',
            name='Link',
        ),
        migrations.AddField(
            model_name='banner_area',
            name='link_url',
            field=models.URLField(blank=True, help_text='Enter internal or external URL to redirect when clicked', null=True),
        ),
    ]
